registry:
  protocol: "zookeeper"
  address: "192.168.126.128:2181"
application:
  name: "simple-demo"
  environment: "develop"
  log_dir: "./logs"
  log_level: "INFO"
parameter:
  version:
  group:
  retry: 0
  timeout: 3
reference:
  - service_name: "php.dubbo.demo.DemoService"
    url: ""
    retry: 0
    timeout: 3
    query:
      - group:
        version:
      - group: "*"
        version: "0.0.1"
  - service_name: "com.ikurento.user.ExportProvider"





